---
name: Build docker image

# This workflow runs when any of the following occur:
# - A push is made to a branch called `main` or `seed`
# - A tag starting with "v" is created
# - A pull request is created or updated
on:
  push:
    branches:
      - main
    tags:
      - v*
  pull_request:
env:
  IMAGE_NAME: netbox-operator
jobs:
  push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Generate docker tag
        id: meta
        uses: docker/metadata-action@v5.5.1
        with:
          images: ${{ env.IMAGE_NAME }}        
          tags: |
            type=schedule
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=ref,event=branch
            type=ref,event=tag
            type=ref,event=pr
            type=sha
      - name: Build and push image
        run: |
          # generate IMAGE_ID
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/
          # This changes all uppercase characters to lowercase.
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
          
          echo IMAGE_ID=$IMAGE_ID
          echo DOCKER_TAG="${{ steps.meta.outputs.tags }}"
          echo DOCKER_LABELS="${{ steps.meta.outputs.labels }}"

          # build and push
          # docker buildx build --platform linux/amd64,linux/arm64 --push --tag "${IMAGE_ID}${{ steps.meta.outputs.tags }}" .
          docker buildx build --platform linux/amd64 --push --tag "${IMAGE_ID}${{ steps.meta.outputs.tags }}" --label "${{ steps.meta.outputs.labels }}" .
          